[package]
name = "thisctx_impl"
version = "0.1.0"
authors = ["loichyan <loichyan@foxmail.com>"]
edition = "2018"
license = "MIT"

description = "Macro implementation of the `thisctx` crate"
repository = "https://github.com/loichyan/thisctx"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"
