[package]
name = "thisctx_impl"
version = "0.4.0"
license = "MIT OR Apache-2.0"
authors = ["loichyan <loichyan@foxmail.com>"]
edition = "2021"
rust-version = "1.56"

description = "Macro implementation of the `thisctx` crate"
readme = "README.md"
repository = "https://github.com/loichyan/thisctx"
documentation = "https://docs.rs/thisctx"

[lib]
proc-macro = true

[dependencies]
plap = { git = "https://github.com/loichyan/plap", rev = "d409630f70bea03197fc45346e6ceabe3ac4c3d0" }
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
