[tool.commitizen]
name = "cz_conventional_commits"
version = "0.3.0"
tag_format = "v$version"
bump_message = "chore(release): v$new_version"
version_files = ["Cargo.toml", "packages/impl/Cargo.toml"]
