[workspace]
members = ["impl"]
exclude = ["compile_tests"]

[package]
name = "thisctx"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["loichyan <loichyan@foxmail.com>"]
edition = "2018"
rust-version = "1.33"

description = "Easily create error with contexts"
readme = "README.md"
repository = "https://github.com/loichyan/thisctx"
documentation = "https://docs.rs/thisctx"

keywords = ["error", "derive"]
categories = ["rust-patterns"]

[dependencies]
thisctx_impl = { path = "impl" }

[dev-dependencies]
thiserror = "1.0"
