[workspace]
members = ["packages/*"]
exclude = ["packages/compile_tests"]

[package]
name = "thisctx"
version = "0.2.0"
license = "MIT OR Apache-2.0"
authors = ["loichyan <loichyan@foxmail.com>"]
edition = "2018"
rust-version = "1.33"

description = "Easily create error with contexts"
readme = "README.md"
repository = "https://github.com/loichyan/thisctx"
documentation = "https://docs.rs/thisctx"

keywords = ["error", "derive"]
categories = ["rust-patterns"]

[dependencies.thisctx_impl]
version = "=0.2.0"
path = "packages/impl"

[dev-dependencies]
thiserror = "1.0"
